[package]
name = "sensei"
version = "1.0.0"
edition = "2021"

[profile.dev]
strip = true
opt-level = 1

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
num_cpus = "1.15.0"
serde_json = "1.0.94"
colored = "2.0.0"
prisma = "0.1.1"
angular-units = "0.2.4"
